# Generated by Django 5.1.1 on 2024-11-09 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6)),
                ('modelo', models.CharField(max_length=30)),
                ('anno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=5)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehiculo_relacionado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.vehiculo')),
            ],
        ),
    ]
