# Generated by Django 5.1.1 on 2024-11-09 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conductor_gps_alter_conductor_vehiculo_relacionado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
        migrations.AlterField(
            model_name='conductor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='gps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.gps'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='vehiculo_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehiculo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='conductor_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.conductor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
