# Generated by Django 5.1.1 on 2024-11-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_usuario_rut_alter_conductor_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
