# Generated by Django 5.1.1 on 2024-11-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_conductor_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductor',
            name='gps',
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='app.conductor')),
            ],
        ),
        migrations.DeleteModel(
            name='GPS',
        ),
    ]
