# Generated by Django 5.1.3 on 2024-11-22 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_conductor_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='conductor_relacionado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.conductor'),
        ),
    ]
