# Generated by Django 5.1.3 on 2024-11-23 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usuario_conductor_relacionado'),
        ('app', '0007_remove_conductor_gps_gpslog_delete_gps'),
    ]

    operations = [
    ]
