# Generated by Django 5.1.3 on 2024-11-23 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20241123_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpslog',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='app.usuario'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='conductor_relacionado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='vehiculo_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.vehiculo'),
        ),
        migrations.DeleteModel(
            name='Conductor',
        ),
    ]
