# Generated by Django 5.1.3 on 2024-11-23 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_gpslog_conductor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='vehiculo_relacionado',
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='app.usuario'),
            preserve_default=False,
        ),
    ]
